### ISSUE TITLE
[EPIC] Reorganization of ClassQuiz organization on GitHub

### ISSUE THREAD

**Issue by Dynnammo** [mawoka-myblock/ClassQuiz#120]
**Describe the change and why it is needed**
Classquiz is a mature enough project to become a distinct organization.
Since many open-source projects use this model to have a clearer appearance for both developers and users : [Decidim](https://github.com/decidim), [Metabase](https://github.com/metabase), [Airbyte](https://github.com/airbytehq?type=source), [Vue](https://github.com/vuejs?type=source)

Currently, the current repo contains _both_ code that makes the quiz run _and_ the code for classquiz presentation (on classquiz.de) and the presentation.

**What would it look like ?**

- An organization called `classquiz` or `classquiz-project`
- For now two repos in it : 
   - the current `mawoka-myblock/classquiz` project, renamed `classquiz` (so accessible at github.com/classquiz/classquiz). This codes continues to be deployed at classquiz.de
   - a `docs` project that contains all  the documentation about the project, but also the presentation of the project. This project could start from the existing infrastructure (Python + Svelte), but I would recommend the use of a docs framework like docusaurus, mkdocs or whatever fits, since it'll ease the accessibilily of modification for non-JS folks.

**Additional context**
Quite a big issue, therefore why it's called an _epic_ since this migration would be in multiple steps to be determined.

Thanks for contributing to ClassQuiz!

**Comment by mawoka-myblock** [comment]
Sorry for saying that, but I am against it. Splitting things into different repos seems unnecessary and would add extra complexity. Keeping one repo for everything is how I want it. I also think that putting the docs somewhere else isn't necessary, since we know that ClassQuiz isn't well documented, except the dev-guide and the self-host guide. We could definitely think about adding a markdown-based documentation-system, but I also think that writing the docs in pure HTML isn't super difficult. Just look at the source-code of the docs-page. Just some boilerplate at the top, below that is just simple HTML.
