### ISSUE TITLE
Move some buttons in navbar to the right

### ISSUE THREAD

**Issue by Vartika511** [mawoka-myblock/ClassQuiz#128]
Hello, Myself a contributor from Hacktoberfest. 

**Describe the bug**
The navbar of the page needs improvement like the login link should be in right side and even search button. The background of the page and the font need to be improved

**Screenshots**
![image](https://user-images.githubusercontent.com/73403577/193219711-7ac328c5-422f-4cb8-aa48-502635a70599.png)

Thanks for contributing to ClassQuiz!

**Comment by LunarMarathon** [comment]
I would like to work on this. @mawoka-myblock What are your thoughts?

**Comment by mawoka-myblock** [comment]
You've mentioned 2 points:
1. The navbar: honestly, I think that it's fine the way it is. Having icons, so that it gets more compact would be cool, but we don't have icons for every link, which are also clearly identifiable.
2. The background doesn't need to be improved, since the green is part of my "brand" (if you want to see it like that).

**Comment by mawoka-myblock** [comment]
What do you think guys? (@Dynnammo)

**Comment by Dynnammo** [comment]
1. Agree on staying with this background color and font family since it isn't what's most urgent as of now. If we add time we could work on a graphic chat that simply set what the primary colors, secondary ones and font families used throughout the software.
2. I agree otherwise on the fact that "login" button (and probably Register also) should move to the right of the navbar. I can write a specific issue about it @mawoka-myblock

@Vartika511 and @LunarMarathon thanks for your thoughts and motivation, count on me to assign and review your issues one issues that may be created next days on this topic. Do not hesitate to go around the software and create other issues if you find anything else troublesome, it helps us a lot.

**Comment by mawoka-myblock** [comment]
> 1. Agree on staying with this background color and font family since it isn't what's most urgent as of now. If we have time we could work on a graphic chat that simply set what the primary colors, secondary ones and font families used throughout the software.
> 
>     2. I agree otherwise on the fact that "login" button (and probably Register also) should move to the right of the navbar. I can write a specific issue about it @mawoka-myblock
> 
> 
> @Vartika511 and @LunarMarathon thanks for your thoughts and motivation, count on me to assign and review your issues one issues that may be created next days on this topic. Do not hesitate to go around the software and create other issues if you find anything else troublesome, it helps us a lot.

Yes, moving the register and login-button to the right, is a good idea, but please do not use the `display: fixed`-approach I've used for the dark-mkde toggle! :D 
Please also remember to check that you will not have broken the mobile-navbar!

**Comment by mawoka-myblock** [comment]
Any progress, @LunarMarathon?

**Comment by Dynnammo** [comment]
Putting myself on the subject @mawoka-myblock , try to do it in the fortnight.
