### ISSUE TITLE
Website uses Cloudflare

### ISSUE THREAD

**Issue by vXtreniusX** [mawoka-myblock/ClassQuiz#155]
**Describe the bug**
The official website (https://classquiz.de/) uses Cloudflare, which is known for issues with privacy, centralization, and accessibility.

The website also mentions that it doesn't track users...

> Kahoot tracks with at least 2 american > 3rd-parties and ClassQuiz doesn't track > with any 3rd-parties at all!

...which is incorrect.

Please see crimeflare.eu.org for more information.

**Comment by mawoka-myblock** [comment]
Yes! Using Cloudflare is less than ideal and I know that cloudflare is a problem, but I can't afford paying for a DNS, CDN or DDoS-protection. I'll test disabling the reverse-proxy and I'll just use Cloudflare-DNS. If everything will be fine, I'll think about switching the DNS-service, otherwise I'll have to keep Cloudflare. Thank you for pointing that out!

**Comment by mawoka-myblock** [comment]
Cloudflare's proxy should now be disabled!
