### ISSUE TITLE
setting a list of allowed domains for the images

### ISSUE THREAD

**Issue by Cameo007** [mawoka-myblock/ClassQuiz#40]
I would think it would be cool if direct links to images and not just imgur links were also accepted for questions.

Many greetings
Cameo007

**Comment by mawoka-myblock** [comment]
> I would think it would be cool if direct links to images and not just imgur links were also accepted for questions.
> 
> Many greetings Cameo007

Hey Cameo007 (btw cool name),
Thanks for opening this issue and sorry for responding later, because I didn't have any mobile connection.
You are totally right! I did this because of one reason: to male sure that the URLs aren't dangerous, because:
1. I don't want to host and validate any potential ly dangerous/illegal pictures
2. I trust Imgur.

What would you do? Do you have any specific site you want to use? Do you want to be able to upload images directly to ClassQuiz?

Yours, Mawoka

**Comment by Cameo007** [comment]
Hi Mawoka,
Actually I use Google Drive but I can also host the image on a website. An upload function would be good, but I understand that you don't want to host and validate any potential ly dangerous/illegal pictures.

**Comment by mawoka-myblock** [comment]
> Hi Mawoka, Actually I use Google Drive but I can also host the image on a website. An upload function would be good, but I understand that you don't want to host and validate any potential ly dangerous/illegal pictures.

What would your solution look like (for the illegal/dangerous content)? I think Google Drive should be OK.

**Comment by Cameo007** [comment]
I don't know, but Google Drive is OK. Thank you.

**Comment by mawoka-myblock** [comment]
Don't be so fast, @Cameo007! The issue isn't yet solved! :D

**Comment by Cameo007** [comment]
Thanks anyway. From the sound of it, you'll try it.

**Comment by mawoka-myblock** [comment]
Sorted out with new editor which supports direct upload.
