### ISSUE TITLE
Separate frontend and backend repository

### ISSUE THREAD

**Issue by awang-karisma** [mawoka-myblock/ClassQuiz#78]
**Describe the change and why it is needed**
Put frontend in different repository to make the codebase clean and clear, also make it easier for new contributor like me to contribute (I am learning frontend dev).

**Additional context**
None

Thanks for contributing to ClassQuiz!

**Comment by mawoka-myblock** [comment]
> **Describe the change and why it is needed** Put frontend in different repository to make the codebase clean and clear, also make it easier for new contributor like me to contribute (I am learning frontend dev).
> 
> **Additional context** None
> 
> Thanks for contributing to ClassQuiz!

Thank you for opening this issue and contributing to ClassQuiz!

I've had the discussion in the past, but I didn't want it, since splitting frontend and backend into 2 repos would  make the development-process less user-friendly, since the frontend doesn't work without the backend. Then, I would have to create an org and I would loose this repo with all the stars, forks and issues.


I still think that the experience for new contributors can (and should) be improved since it's not up-to-date anymore (I think). If you got any questions or if the docs are wrong/not clear enough, ask me!

**Comment by awang-karisma** [comment]
Alright, thanks for the explanation, now I understand the reason why some projects didn't separate backend and frontend.

I will try to fork and run on my pc and see if I could make it work.
